[features]
seeds = false
skip-lint = false
[programs.localnet]
carstore = "G7XMcMqA1163mYCQdLwoTaBA9PYS1eZePViaRnWprc9f"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/khanhle/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
